// Client
export const API_REQUEST = 'API_REQUEST'
export const CHANGE_ACCESS_TOKEN = 'CHANGE_ACCESS_TOKEN'
export const CHANGE_SECRET_TOKEN = 'CHANGE_SECRET_TOKEN'
export const CHANGE_ZONE = 'CHANGE_ZONE'
export const CHANGE_METHOD = 'CHANGE_METHOD'
export const CHANGE_URI = 'CHANGE_URI'
export const CHANGE_PARAMS = 'CHANGE_PARAMS'

// API List
export const SELECT_API = 'SELECT_API'

// History
export const SELECT_HISTORY = 'SELECT_HISTORY'
export const DELETE_HISTORY = 'DELETE_HISTORY'

// Settings
export const CHANGE_SETTINGS_SAVETO = 'CHANGE_SETTINGS_SAVETO'

