export const API_REQUEST = 'API_REQUEST'

export const SELECT_API = 'SELECT_API'
export const SELECT_HISTORY = 'SELECT_HISTORY'

export const CHANGE_ZONE = 'CHANGE_ZONE'
export const CHANGE_METHOD = 'CHANGE_METHOD'
export const CHANGE_URI = 'CHANGE_URI'
export const CHANGE_PARAMS = 'CHANGE_PARAMS'
