nginx:
  build: nginx
  volumes:
    - ../dist:/root/www
    - ../keys:/etc/nginx/keys
  ports:
    - "80:80"
    - "443:443"
node:
  build: node
  volumes:
    - ../server:/root/server
    - ../:/root
  ports:
    - "3000:3000"
